#!/usr/bin/env python3
"""Convert browser-exported JSON cookies to Netscape format for curl --cookie.

Reads a JSON array of cookie objects from stdin or a file, writes Netscape-format
cookie file to stdout. Output is suitable for curl's -b/--cookie flag.

Input format (Firefox/Chrome cookie export):
  [{"Host raw": "...", "Name raw": "...", "Path raw": "...",
    "Content raw": "...", "Expires raw": "...", "Send for raw": "...",
    "This domain only raw": "...", ...}, ...]

Output format (Netscape):
  domain  flag  path  secure  expiration  name  value

Usage:
  python3 convert-cookies.py [cookies.json]  > cookies.txt
"""

import json
import sys
import urllib.parse
from pathlib import Path


def strip_protocol(host: str) -> str:
    """Remove https:// or http:// prefix and trailing slash from host."""
    for prefix in ("https://", "http://"):
        if host.startswith(prefix):
            host = host[len(prefix):]
            break
    return host.rstrip("/")


def ns_cookie_domain(host: str, host_only: bool) -> str:
    """Build the Netscape domain field.

    Netscape format: leading dot means valid for subdomains.
    host_only=true  → no leading dot (only this exact host).
    host_only=false → leading dot (valid for subdomains).
    """
    domain = strip_protocol(host)
    if host_only:
        return domain
    if not domain.startswith("."):
        domain = f".{domain}"
    return domain


def ns_flag(host_only: bool) -> str:
    """Netscape flag: TRUE if all machines in domain can access (subdomain matching)."""
    return "FALSE" if host_only else "TRUE"


def ns_secure(send_for_raw: str) -> str:
    """Map Send for raw to Netscape secure flag.

    Send for raw:
      "true"  → encrypted connections only  → TRUE
      "false" → any type of connection      → FALSE
    """
    return "TRUE" if send_for_raw.strip().lower() == "true" else "FALSE"


def url_decode(value: str) -> str:
    """URL-decode a cookie value if it appears percent-encoded."""
    if "%" in value:
        try:
            return urllib.parse.unquote(value)
        except Exception:
            return value
    return value


def convert(entries: list[dict]) -> list[str]:
    """Convert a list of cookie dicts to Netscape lines."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by swain-search/convert-cookies.py", ""]
    for c in entries:
        host = c.get("Host raw", "")
        name = c.get("Name raw", "")
        path = c.get("Path raw", "/")
        content = url_decode(c.get("Content raw", ""))
        expires = c.get("Expires raw", "0")
        send_for = c.get("Send for raw", "false")
        host_only_raw = c.get("This domain only raw", "true")

        host_only = host_only_raw.strip().lower() == "true"

        domain = ns_cookie_domain(host, host_only)
        flag = ns_flag(host_only)
        secure = ns_secure(send_for)

        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{content}")
    return lines


def main() -> None:
    args = sys.argv[1:]
    if args:
        with open(args[0]) as f:
            data = json.load(f)
    else:
        data = json.load(sys.stdin)

    if isinstance(data, dict):
        data = [data]
    if not isinstance(data, list):
        print("ERROR: expected a JSON array of cookie objects", file=sys.stderr)
        sys.exit(1)

    for line in convert(data):
        print(line)


if __name__ == "__main__":
    main()
